# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92765f7d25f50daca82cb5cb25e0db1579dd0add8ad6b2a8ab66cf6b141667f9e1242be6082e19fc8bf09252a5d73a56e28581895db06aeb0103a213a4dbeaaf

test:
  secret_key_base: ac629864c42390ac720690acfa1842f31bff8ccb279eef108f0c24336a8173e4cc188cb4769fa49fac99f21d7e214c5f564e276bac9592a7c6623026e9e58869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
